-- Run this in your Supabase SQL Editor
create table officials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  position text,
  category text,
  status text default 'current',
  nationality text default 'غير محدد',
  appointment_date date,
  photo_url text,
  latest_news jsonb default '[]'::jsonb
);
insert into storage.buckets (id, name, public) values ('official-photos', 'official-photos', true);
create policy "Public Access" on storage.objects for select using ( bucket_id = 'official-photos' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'official-photos' );
