-- Run this in your Supabase SQL Editor to set up the DB

-- 1. Create the main officials table
create table officials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  position text,
  category text,
  status text default 'current',
  nationality text default 'غير محدد',
  appointment_date date,
  photo_url text,
  bio text,
  mandates jsonb default '[]'::jsonb,
  social_stats jsonb default '{"tweets": 0, "videos": 0, "news": 0}'::jsonb,
  latest_news jsonb default '[]'::jsonb,
  predecessors jsonb default '[]'::jsonb,
  is_counterpart boolean default false
);

-- 2. Create the Storage Bucket for photos
insert into storage.buckets (id, name, public) 
values ('official-photos', 'official-photos', true);

-- 3. Set up Storage Policies (Allow public read, authenticated insert)
-- Note: For this demo, we allow public insert to make testing easier without auth
-- In production, create RLS policies for uploads.

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'official-photos' );

create policy "Public Upload"
  on storage.objects for insert
  with check ( bucket_id = 'official-photos' );
